FROM nvidia/cuda:10.2-cudnn7-runtime-ubuntu18.04

# Set up locale to prevent bugs with encoding
ENV LC_ALL=C.UTF-8 LANG=C.UTF-8

RUN apt-get update || true && apt-get install -y \
    wget curl git \
    libglib2.0-0 libsm6 libxext6 libxrender-dev \
    python3 python3-pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN cd /usr/bin \
    && ln -s python3 python \
    && ln -s pip3 pip

WORKDIR /workspace
